// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
)

type User struct {
	Name     sql.NullString
	Email    sql.NullString
	Password sql.NullString
}
